#!/bin/bash

clear;

echo "##################################################"
echo "#####      INICIANDO O TESTE DE PING AO      #####"
echo "#####          SITE: www.google.com          #####"
echo "##################################################"

while [[ 3 -eq 3 ]] ;
do

	ping www.google.com | grep --color "time="

done
